#!/bin/bash
# Shared library — functions and runtime paths for the bridge rotation system.
# Source this file from other scripts:  source "$(dirname "$0")/lib.sh"
# Do not edit this file; edit config.sh for user settings.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.sh"

# --- Derived paths (based on script location, not user-configurable) ---
WORKING_DIR="$SCRIPT_DIR"
REPO_DIR="$WORKING_DIR/repo"
LOG_FILE="$WORKING_DIR/updater.log"
FAIL_LOG="$WORKING_DIR/failed_bridges.log"
LOCK_FILE="$WORKING_DIR/rotate.lock"

# Ensure working directory exists
mkdir -p "$WORKING_DIR"

# --- Logging ---
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE" >&2
}

# --- Bridge testing function ---
# Tests a single obfs4 bridge by launching a temporary tor instance.
# Outputs the bridge line on stdout ONLY on success (Bootstrapped 100%).
# Returns 0 on success, 1 on failure.
# Monitors tor output in real-time — kills tor immediately on success
# instead of waiting for the full timeout.
# Must be exported for parallel execution via check_bridges_batch.
check_bridge() {
    local bridge="$1"
    local temp_dir
    temp_dir=$(mktemp -d "/tmp/tor-check-XXXXXX")
    local tor_log="$temp_dir/tor_output.log"

    # Ensure cleanup even if killed
    trap "rm -rf '$temp_dir'" EXIT

    # tor runs as 'tor' user — it must own the data directory
    chown tor:tor "$temp_dir" 2>/dev/null || true
    chmod 700 "$temp_dir"

    # Start tor in background, capture output to log
    tor \
        --UseBridges 1 \
        --Bridge "$bridge" \
        --Log "notice stdout" \
        --DataDirectory "$temp_dir" \
        --SocksPort auto \
        --CircuitBuildTimeout 30 \
        > "$tor_log" 2>&1 &
    local tor_pid=$!

    local found=0
    local deadline=$((SECONDS + TIMEOUT))

    # Poll the log until success, tor dies, fatal error, or deadline
    while [ "$SECONDS" -lt "$deadline" ]; do
        if grep -q "Bootstrapped 100%" "$tor_log" 2>/dev/null; then
            echo "$bridge"
            found=1
            break
        fi
        # Early abort: bridge is definitively unreachable
        if grep -qE "unable to connect OR connection|general SOCKS server failure" "$tor_log" 2>/dev/null; then
            break
        fi
        if ! kill -0 "$tor_pid" 2>/dev/null; then
            break   # tor exited on its own (failure)
        fi
        sleep 0.5
    done

    # Cleanup
    if [ "$found" -eq 0 ]; then
        # Save failure log for debugging
        {
            echo "===== [$(date '+%Y-%m-%d %H:%M:%S')] $bridge ====="
            cat "$tor_log"
            echo "====================="
        } >> "$FAIL_LOG"
    fi

    kill "$tor_pid" 2>/dev/null
    wait "$tor_pid" 2>/dev/null
    rm -rf "$temp_dir"

    return $((1 - found))
}

export -f check_bridge
export TIMEOUT FAIL_LOG

# --- Parallel bridge checker ---
# Reads bridges from stdin (one per line), tests them in parallel,
# outputs only working bridges to stdout (one per line).
# Optional $1: target count — stops early once this many working bridges found.
#              Pass 0 or omit to test all.
# Logs progress to LOG_FILE.
check_bridges_batch() {
    local target="${1:-0}"
    local input
    input=$(cat)

    local total
    total=$(echo "$input" | grep -c . || echo 0)

    if [ "$total" -eq 0 ]; then
        return 0
    fi

    log "Testing bridges (max $MAX_JOBS parallel, timeout ${TIMEOUT}s, target: ${target:-all})..."

    local result_file
    result_file=$(mktemp)
    local running=0
    local collected=0

    while IFS= read -r bridge; do
        [ -z "$bridge" ] && continue

        # Wait for a free slot if at max capacity
        while [ "$running" -ge "$MAX_JOBS" ]; do
            wait -n 2>/dev/null || true
            running=$((running - 1))

            if [ "$target" -gt 0 ]; then
                collected=$(wc -l < "$result_file" 2>/dev/null || echo 0)
                if [ "$collected" -ge "$target" ]; then
                    log "Reached target ($target working bridges) — stopping early"
                    jobs -p 2>/dev/null | xargs kill 2>/dev/null || true
                    wait 2>/dev/null || true
                    break 2
                fi
            fi
        done

        check_bridge "$bridge" >> "$result_file" 2>/dev/null &
        running=$((running + 1))
    done <<< "$input"

    # Wait for remaining jobs to finish
    wait 2>/dev/null || true

    local result
    result=$(cat "$result_file" 2>/dev/null || true)
    local count
    count=$(echo "$result" | grep -c . || echo 0)
    log "Found $count working bridge(s)"

    rm -f "$result_file"
    echo "$result"
}

# --- Extract obfs4 bridges from a file ---
# Ignores comments and empty lines.
extract_obfs4() {
    local file="$1"
    grep -v '^#' "$file" | grep 'obfs4' || true
}
